### ISSUE TITLE
Client timeout configuration

### ISSUE THREAD

**Issue by pofider** [hedonCZ/jsreport-javaclient#9]
The client timeout defaults likely to the 10s. That is too low for the report generation. I would think 100s is a good default.
Also, the client timeout should be configurable and exposed in JsReportService.

**Comment by hedonCZ** [comment]
Fixed in 1.0.10. Check classes [ServiceTimeout](https://github.com/hedonCZ/jsreport-javaclient/blob/master/src/main/java/net/jsreport/java/service/ServiceTimeout.java) and [JsReportService](https://github.com/hedonCZ/jsreport-javaclient/blob/master/src/main/java/net/jsreport/java/service/JsReportService.java).

**Comment by pofider** [comment]
This can be closed now. Thank you.
